version: "3.9"
services:
  accessbot:
    image: public.ecr.aws/strongdm/accessbot:latest
    env_file:
      # You could use env-file.example as a reference
      - env-file
    ports:
      - 3141:3141
      - 3142:3142
